# Generated by Django 2.2.12 on 2020-07-10 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_registration',
            name='a_photo',
            field=models.FileField(max_length=355, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='patient_registration',
            name='p_photo',
            field=models.FileField(max_length=355, null=True, upload_to=''),
        ),
    ]
