# Generated by Django 2.2.12 on 2020-07-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_billheader'),
    ]

    operations = [
        migrations.CreateModel(
            name='billdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BillCode', models.IntegerField(null=True)),
                ('LineNo', models.IntegerField(null=True)),
                ('SerDept', models.IntegerField(null=True)),
                ('SerCode', models.IntegerField(null=True)),
                ('SubSerCode', models.IntegerField(null=True)),
                ('Qty', models.IntegerField(null=True)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('TotalAmount', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('DrCode', models.IntegerField(null=True)),
                ('DrShare', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('DrDisc', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('ReferCode', models.IntegerField(null=True)),
                ('ReferShare', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('ReferDisc', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('HospShare', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('HospDisc', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('NetAmount', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('PaidAmount', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Balance', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('VisitType', models.CharField(max_length=32, null=True)),
                ('TPAApplicable', models.BooleanField(default=True)),
                ('IsActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='billreceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BillCode', models.IntegerField(null=True)),
                ('RecNo', models.CharField(max_length=32, null=True)),
                ('RecDateTime', models.DateTimeField(auto_now_add=True)),
                ('RecDate', models.CharField(max_length=32, null=True)),
                ('RecTime', models.CharField(max_length=32, null=True)),
                ('RecAmount', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Cash', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('CardType', models.CharField(max_length=32, null=True)),
                ('CardBank', models.IntegerField(null=True)),
                ('CardNo', models.CharField(max_length=32, null=True)),
                ('Card', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Transfee', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('CardTotal', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('OtherPayType', models.CharField(max_length=32, null=True)),
                ('OtherPayNo', models.CharField(max_length=32, null=True)),
                ('OtherBank', models.IntegerField(null=True)),
                ('OtherPaid', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('OtherDate', models.DateTimeField(auto_now_add=True)),
                ('RecMode', models.CharField(max_length=32, null=True)),
                ('AddedBy', models.CharField(max_length=32, null=True)),
                ('AddedDate', models.DateTimeField(auto_now_add=True)),
                ('EditedBy', models.CharField(max_length=32, null=True)),
                ('EditedDate', models.DateTimeField(auto_now_add=True)),
                ('CancelBy', models.CharField(max_length=32, null=True)),
                ('CancelDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
