# Generated by Django 3.0.5 on 2020-12-07 06:42

from django.db import migrations, models
import transactions.models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_billdetails_billreceipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billheader',
            name='BillNo',
            field=models.CharField(default=transactions.models.generet_billNO, max_length=32, null=True),
        ),
    ]
