# Generated by Django 3.0.5 on 2020-12-07 07:14

from django.db import migrations, models
import transactions.models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_auto_20201207_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billheader',
            name='BillDate',
            field=models.CharField(default=transactions.models.str_date, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='billheader',
            name='BillTime',
            field=models.CharField(default=transactions.models.str_time, max_length=32, null=True),
        ),
    ]
