# Generated by Django 2.2.12 on 2020-05-30 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('priority', models.IntegerField()),
                ('isActive', models.BooleanField()),
                ('addedBy', models.CharField(max_length=32)),
                ('addedDate', models.DateTimeField()),
                ('editedBy', models.CharField(max_length=32)),
                ('editedDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SubDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subDepartment', models.CharField(max_length=25)),
                ('priority', models.IntegerField()),
                ('isActive', models.BooleanField()),
                ('addedBy', models.CharField(max_length=32)),
                ('addedDate', models.DateTimeField()),
                ('editedBy', models.CharField(max_length=32)),
                ('editedDate', models.DateTimeField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.Department')),
            ],
        ),
    ]
