# Generated by Django 2.2.12 on 2020-05-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='addedBy',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='addedDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='editedBy',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='editedDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
