# Generated by Django 2.2.12 on 2020-06-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_auto_20200530_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='generalType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genType', models.CharField(max_length=32)),
                ('genValue', models.CharField(max_length=32)),
                ('isActive', models.BooleanField()),
                ('addedBy', models.CharField(max_length=32, null=True)),
                ('addedDate', models.DateTimeField(auto_now_add=True)),
                ('editedBy', models.CharField(max_length=32, null=True)),
                ('editedDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
