# Generated by Django 2.2.12 on 2020-06-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_auto_20200530_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdepartment',
            name='addedBy',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='subdepartment',
            name='addedDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subdepartment',
            name='editedBy',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='subdepartment',
            name='editedDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
