# Generated by Django 2.2.12 on 2020-06-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_remove_packagemapping_packcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagemapping',
            name='PackCode',
            field=models.IntegerField(null=True),
        ),
    ]
