# Generated by Django 2.2.12 on 2020-06-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_generaltype'),
    ]

    operations = [
        migrations.CreateModel(
            name='registrationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regType', models.CharField(max_length=32)),
                ('regFee', models.IntegerField()),
                ('renevalFee', models.IntegerField()),
                ('isActive', models.BooleanField()),
                ('addedBy', models.CharField(max_length=32, null=True)),
                ('addeddate', models.DateTimeField(auto_now_add=True)),
                ('editedby', models.CharField(max_length=32, null=True)),
                ('editeddate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
