# Generated by Django 2.2.12 on 2020-06-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_registrationtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='discounType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discType', models.CharField(max_length=32)),
                ('discount', models.IntegerField()),
                ('userId', models.IntegerField(null=True)),
                ('password', models.CharField(max_length=32)),
                ('isActive', models.BooleanField()),
                ('addedBY', models.CharField(max_length=32, null=True)),
                ('addeddate', models.DateTimeField(auto_now_add=True)),
                ('editedby', models.CharField(max_length=32, null=True)),
                ('editeddate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
