# Generated by Django 2.2.12 on 2020-06-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_discountype'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=32, null=True)),
                ('password', models.CharField(max_length=32, null=True)),
                ('fullName', models.CharField(max_length=32, null=True)),
                ('empCode', models.CharField(max_length=32, null=True)),
                ('department', models.CharField(max_length=32, null=True)),
                ('user', models.CharField(max_length=32, null=True)),
                ('counter', models.CharField(max_length=32, null=True)),
                ('mobileno', models.CharField(max_length=32, null=True)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=32, null=True)),
                ('marital', models.CharField(max_length=32, null=True)),
                ('date_of_birth', models.CharField(max_length=32, null=True)),
                ('emailid', models.CharField(max_length=32, null=True)),
                ('photo', models.CharField(max_length=32, null=True)),
                ('relationtype', models.CharField(max_length=32, null=True)),
                ('relationname', models.CharField(max_length=32, null=True)),
                ('alternateContact', models.CharField(max_length=32, null=True)),
                ('address', models.CharField(max_length=32, null=True)),
                ('isactive', models.BooleanField(null=True)),
                ('addedBY', models.CharField(max_length=32, null=True)),
                ('addeddate', models.DateTimeField(auto_now_add=True)),
                ('editedby', models.CharField(max_length=32, null=True)),
                ('editeddate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
