# Generated by Django 2.2.12 on 2020-06-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0006_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='income_expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=32, null=True)),
                ('particular', models.CharField(max_length=32, null=True)),
                ('isActive', models.BooleanField()),
                ('addedBY', models.CharField(max_length=32, null=True)),
                ('addeddate', models.DateTimeField(auto_now_add=True)),
                ('editedby', models.CharField(max_length=32, null=True)),
                ('editeddate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
