# Generated by Django 2.2.12 on 2020-06-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_income_expenses'),
    ]

    operations = [
        migrations.CreateModel(
            name='hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospitalName', models.CharField(max_length=32, null=True)),
                ('address1', models.CharField(max_length=32, null=True)),
                ('address2', models.CharField(max_length=32, null=True)),
                ('shortName', models.CharField(max_length=32, null=True)),
                ('phone', models.CharField(max_length=32, null=True)),
                ('FAX', models.CharField(max_length=32, null=True)),
                ('pincode', models.CharField(max_length=32, null=True)),
                ('Logo1', models.CharField(max_length=32, null=True)),
                ('Logo2', models.CharField(max_length=32, null=True)),
                ('isActive', models.BooleanField()),
                ('addedBY', models.CharField(max_length=32, null=True)),
                ('addeddate', models.DateTimeField(auto_now_add=True)),
                ('editedby', models.CharField(max_length=32, null=True)),
                ('editeddate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
