# Generated by Django 2.2.12 on 2020-06-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0008_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='professional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, null=True)),
                ('professionalName', models.CharField(max_length=32, null=True)),
                ('qualification', models.CharField(max_length=32, null=True)),
                ('designation', models.CharField(max_length=32, null=True)),
                ('deptId', models.IntegerField(null=True)),
                ('category', models.CharField(max_length=32, null=True)),
                ('OPNewVisit', models.IntegerField(null=True)),
                ('OPRevisit', models.IntegerField(null=True)),
                ('OPfollowup', models.IntegerField(null=True)),
                ('OPShare', models.DecimalField(decimal_places=2, max_digits=5)),
                ('OPShareamount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('IPAmount', models.IntegerField(null=True)),
                ('IPShare', models.DecimalField(decimal_places=2, max_digits=5)),
                ('IPShareamount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('licenceNo', models.CharField(max_length=32, null=True)),
                ('photo', models.CharField(max_length=32, null=True)),
                ('contactNo', models.CharField(max_length=32, null=True)),
                ('email', models.CharField(max_length=32, null=True)),
                ('hospitalName', models.CharField(max_length=32, null=True)),
                ('priority', models.IntegerField(null=True)),
                ('token', models.BooleanField(null=True)),
                ('appointment', models.BooleanField(null=True)),
                ('duration', models.IntegerField(null=True)),
                ('isActive', models.BooleanField()),
                ('addedBY', models.CharField(max_length=32, null=True)),
                ('addeddate', models.DateTimeField(auto_now_add=True)),
                ('editedby', models.CharField(max_length=32, null=True)),
                ('editeddate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
