# Generated by Django 2.2.12 on 2020-06-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0009_professional'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MenuName', models.CharField(max_length=32, null=True)),
                ('MenuIcon', models.CharField(max_length=32, null=True)),
                ('priority', models.IntegerField(null=True)),
                ('isActive', models.BooleanField()),
                ('addedBY', models.CharField(max_length=32, null=True)),
                ('addeddate', models.DateTimeField(auto_now_add=True)),
                ('editedby', models.CharField(max_length=32, null=True)),
                ('editeddate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='professional',
            name='IPShare',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='professional',
            name='IPShareamount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='professional',
            name='OPShare',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='professional',
            name='OPShareamount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
