# Generated by Django 2.2.12 on 2020-06-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0010_auto_20200606_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='pagemaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pageName', models.CharField(max_length=32, null=True)),
                ('menuid', models.CharField(max_length=32, null=True)),
                ('submenuName', models.CharField(max_length=32, null=True)),
                ('url', models.CharField(max_length=32, null=True)),
                ('priority', models.IntegerField(null=True)),
                ('isActive', models.BooleanField()),
                ('addedBY', models.CharField(max_length=32, null=True)),
                ('addeddate', models.DateTimeField(auto_now_add=True)),
                ('editedby', models.CharField(max_length=32, null=True)),
                ('editeddate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
