# Generated by Django 2.2.12 on 2020-06-09 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_auto_20200606_1626'),
        ('masters', '0011_pagemaster'),
    ]

    operations = [
    ]
