# Generated by Django 2.2.12 on 2020-06-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0013_area_city_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.FileField(max_length=355, null=True, upload_to='media'),
        ),
    ]
