# Generated by Django 2.2.12 on 2020-06-16 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0016_auto_20200615_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='Logo1',
            field=models.FileField(max_length=355, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='Logo2',
            field=models.FileField(max_length=355, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='address1',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='address2',
            field=models.TextField(max_length=32, null=True),
        ),
    ]
