# Generated by Django 2.2.12 on 2020-06-16 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0017_auto_20200616_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='photo',
            field=models.FileField(max_length=355, null=True, upload_to=''),
        ),
    ]
