# Generated by Django 2.2.12 on 2020-06-16 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0018_auto_20200616_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='address1',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='address2',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
