# Generated by Django 2.2.12 on 2020-06-16 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0019_auto_20200616_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaltype',
            name='name',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
